# Generated by Django 5.2.4 on 2025-08-17 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=128)),
                ('phone_no', models.CharField(max_length=15, unique=True)),
                ('loggedIn', models.BooleanField(default=False)),
            ],
        ),
    ]
