# Generated by Django 5.2.4 on 2025-08-17 06:14

import django.db.models.deletion
import properties.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('urbanlytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField()),
                ('sqft', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('propertyType', models.CharField(choices=[('1BHK', '1 BHK'), ('2BHK', '2 BHK'), ('3BHK', '3 BHK'), ('4BHK', '4 BHK')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('hall', models.ImageField(upload_to=properties.models.user_directory_path)),
                ('kitchen', models.ImageField(upload_to=properties.models.user_directory_path)),
                ('bathroom', models.ImageField(upload_to=properties.models.user_directory_path)),
                ('bedroom1', models.ImageField(blank=True, null=True, upload_to=properties.models.user_directory_path)),
                ('bedroom2', models.ImageField(blank=True, null=True, upload_to=properties.models.user_directory_path)),
                ('bedroom3', models.ImageField(blank=True, null=True, upload_to=properties.models.user_directory_path)),
                ('bedroom4', models.ImageField(blank=True, null=True, upload_to=properties.models.user_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='urbanlytics.user')),
            ],
        ),
    ]
