# Generated by Django 5.2.4 on 2025-08-18 17:00

import properties.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bathroom',
            field=models.ImageField(upload_to=properties.models.upload_to_bathroom),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedroom1',
            field=models.ImageField(blank=True, null=True, upload_to=properties.models.upload_to_bedroom1),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedroom2',
            field=models.ImageField(blank=True, null=True, upload_to=properties.models.upload_to_bedroom2),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedroom3',
            field=models.ImageField(blank=True, null=True, upload_to=properties.models.upload_to_bedroom3),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedroom4',
            field=models.ImageField(blank=True, null=True, upload_to=properties.models.upload_to_bedroom4),
        ),
        migrations.AlterField(
            model_name='property',
            name='hall',
            field=models.ImageField(upload_to=properties.models.upload_to_hall),
        ),
        migrations.AlterField(
            model_name='property',
            name='kitchen',
            field=models.ImageField(upload_to=properties.models.upload_to_kitchen),
        ),
    ]
